#!/bin/bash

import network
import time

#----Network ID Information-----

ssid = "******"
password = "*****"

#-------------------------------

#-----Wi-Fi station interface-----
wlan = network.WLAN(network.STA_IF)

wlan.active(True)

print ("Attempting to connect to WiFi network:", ssid)

#----- This will check if it is already conntected-------

if not wlan.isconntected():
    wlan.conntect(ssid, password)
    
    max_wait_seconds = 15
    start_time = time.ticks_ms()

    print ("Conntecting", end="")
    while not wlan.isconnected() and time.ticks_diff(time.ticks_ms(), start_time) < max_wait_seconds * 1000:
        print(".", end="")
        time.sleep(1)
    print()

if wlan.isconnected():
    print("WiFi connected successfully!")
    network_config = wlan.ifconfig()
    print("IP address:", network_config[0])

else:
    print("Failed to connect to Wifi.")

#---- This is where I will configure MQTT-----